# Generated by Django 4.1.4 on 2022-12-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_alter_video_video_id"),
        ("playlists", "0004_alter_playlist_video"),
    ]

    operations = [
        migrations.RemoveField(model_name="playlist", name="videos",),
        migrations.AlterField(
            model_name="playlist",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlist_featured",
                to="videos.video",
            ),
        ),
    ]
