# Generated by Django 4.1.4 on 2022-12-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_alter_video_video_id"),
        ("playlists", "0005_remove_playlist_videos_alter_playlist_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playlists.playlist",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.video"
                    ),
                ),
            ],
            options={"ordering": ["order", "-timestamp"],},
        ),
        migrations.AddField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                blank=True,
                related_name="playlist_item",
                through="playlists.PlaylistItem",
                to="videos.video",
            ),
        ),
    ]
