# Generated by Django 4.1.4 on 2022-12-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0006_playlistitem_playlist_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist", name="order", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="playlist",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="playlists.playlist",
            ),
        ),
    ]
