# Generated by Django 4.1.4 on 2022-12-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("playlists", "0012_playlist_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlists",
                to="categories.category",
            ),
        ),
    ]
