# Generated by Django 4.1.4 on 2022-12-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProxy",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("videos.video",),
        ),
    ]
