# Generated by Django 4.1.4 on 2022-12-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_videoproxy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videoproxy",
            options={
                "verbose_name": "Published Videos",
                "verbose_name_plural": "Published Videos",
            },
        ),
    ]
