# Generated by Django 4.1.4 on 2022-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_videoproxy_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="video", name="active", field=models.BooleanField(default=True),
        ),
    ]
