# Generated by Django 4.1.4 on 2022-12-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_video_active"),
    ]

    operations = [
        migrations.DeleteModel(name="VideoProxy",),
        migrations.CreateModel(
            name="VideoAllProxy",
            fields=[],
            options={
                "verbose_name": "All Videos",
                "verbose_name_plural": "All Videos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("videos.video",),
        ),
        migrations.CreateModel(
            name="VideoPublishedProxy",
            fields=[],
            options={
                "verbose_name": "Published Videos",
                "verbose_name_plural": "Published Videos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("videos.video",),
        ),
    ]
