# Generated by Django 4.1.4 on 2022-12-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_delete_videoproxy_videoallproxy_videopublishedproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="state",
            field=models.CharField(
                choices=[("PU", "Published"), ("DR", "Draft")],
                default="DR",
                max_length=2,
            ),
        ),
    ]
