# Generated by Django 4.1.4 on 2022-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_video_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
