# Generated by Django 4.1.4 on 2022-12-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_video_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video", old_name="timestamp", new_name="publish_timestamp",
        ),
    ]
